//GLOBAL CONSTANTS

//Creep type count
global.MY_MAX_HARVESTERS = 5;
global.MY_MAX_UPGRADERS = 4;
global.MY_MAX_BUILDERS = 5;
global.MY_MAX_MOVERS = 3;
global.MY_MAX_CLAIMERS = 0;
global.MY_MAX_HEALERS = 2;
global.MY_MAX_DEFENDERS = 1;

//Amount of movers allowed per source
global.MY_MOVERS_PER_SOURCE = 1;

//Room names
//global.MY_MINING_ROOMS = ['W11N46']
//global.MY_SAFEROOMS = ['W11N46'];

//global.MY_SPAWN_ROOMS = ['W11N46'];

//setting home sources
//global.MY_SOURCES = ['58dbc5428283ff5308a402b7','58dbc5448283ff5308a402f7','58dbc5448283ff5308a402f5','58dbc5428283ff5308a402b5','58dbc5448283ff5308a402f3'];
//global.MY_SOURCES = {'E84N97':['58dbc5428283ff5308a402b7','58dbc5448283ff5308a402f7','58dbc5448283ff5308a402f5','58dbc5428283ff5308a402b5','58dbc5448283ff5308a402f3']
//};
//global.MY_OUTER_SOURCES = ['58dbc5448283ff5308a402f5','58dbc5428283ff5308a402b5','58dbc5448283ff5308a402f1','58dbc5448283ff5308a402f3','58dbc5418283ff5308a402b2'];


//roles
//ECONOMY
global.MY_ROLE_UPGRADER = 'upgrader';
global.MY_ROLE_HARVESTER = 'harvester';
global.MY_ROLE_BUILDER = 'builder';
global.MY_ROLE_DECONSTRUCTOR = 'deconstructor';
global.MY_ROLE_MOVER = 'mover';
global.MY_ROLE_CLAIMER = 'claimer';
//WARTIME
global.MY_ROLE_DEFENDER= 'defender';
global.MY_ROLE_HEALER = 'healer';

//ACTIONS
global.MY_ACTION_RETRIEVE = 'retrieve';
global.MY_ACTION_HARVEST = 'harvest';
global.MY_ACTION_DROPOFF = 'deposit';
global.MY_ACTION_BUILD = 'build';
global.MY_ACTION_REPAIR = 'repair';



global.MY_TIER2_BODY_TYPES = {
    'claimer' : [CLAIM,CLAIM,MOVE,MOVE],
    'harvester' : [WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
    'builder' : [CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'mover' : [CARRY,CARRY,CARRY,WORK,MOVE,MOVE,MOVE],
    'upgrader' : [WORK,WORK,CARRY,CARRY,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    'healer' : [TOUGH,TOUGH,TOUGH,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,MOVE],
    'defender' : [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,MOVE,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
};

//Body types
//RC3
global.MY_TIER3_BODYTYPES = {
    'claimer' : [CLAIM,CLAIM,MOVE,MOVE],
    'harvester' : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,MOVE,MOVE],
    'builder' : [WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    'mover' : [WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'upgrader' : [WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE]
};
////////////////////////////////////////////////////////////////////////////////
//RC4
global.MY_TIER4_BODY_TYPES = {
    'claimer' : [CLAIM,CLAIM,MOVE,MOVE],
    'harvester' : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,MOVE,CARRY,CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE],
    'builder' : [CARRY,CARRY,CARRY,CARRY,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'mover' : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'upgrader' : [WORK,WORK,CARRY,CARRY,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    'healer' : [TOUGH,TOUGH,TOUGH,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,MOVE],
    'defender' : [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,MOVE,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
};
//RC5
global.MY_TIER5_BODY_TYPES = {
    'claimer' : [CLAIM,CLAIM,MOVE,MOVE],
    'harvester' : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,MOVE,CARRY,CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE],
    'builder' : [WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'mover' : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'upgrader' : [WORK,WORK,CARRY,CARRY,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    'healer' : [TOUGH,TOUGH,TOUGH,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,MOVE],
    'defender' : [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,MOVE,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
};

global.MY_TIER6_BODY_TYPES = {
    'claimer' : [CLAIM,CLAIM,MOVE,MOVE],
    'harvester' : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,MOVE,CARRY,CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE],
    'builder' : [WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'mover' : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'upgrader' : [WORK,WORK,CARRY,CARRY,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    'healer' : [TOUGH,TOUGH,TOUGH,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,MOVE],
    'defender' : [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,MOVE,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
};


//minimum amount allowed in storage
global.MY_MIN_STORAGE_RATIO = 0.04;
//Repair percents
global.MY_MIN_REPAIR_PERCENT = {
    'road' : 0.5,
    'rampart' : 0.01,
    'constructedWall' : 0.0002,
    'container' : 0.7,
    'spawn' : 1,
    'extension' : 1,
    'tower' : 1
};
